### ISSUE TITLE
Colors named using forward slashes and lose half of their name.

### ISSUE THREAD

**Issue by nimbling** [kaleidocode-app/navigator#1]
I have a bunch of colors named:

Yellow/Primary
Red/Primary
etc.

In navigator, they currently both show up as:

rimary
rimary

I could not find (in the code) where to make sure it escapes that string better, could you perhaps?

Thanks a lot! :)

**Comment by misolori** [comment]
@nimbling you found a bug 😄 I think this should be an easy fix, will take a look.

**Comment by misolori** [comment]
There was a bug in the matching of the `/` character, fixed this so this should now work:

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/35271042/67427724-890e7580-f591-11e9-839c-62afd1dc949c.png">

**Comment by nimbling** [comment]
Sweet! - thank you so much!

One thing, I'm afraid it broke something else :(

I'll PM you a link to my file. I think it's something with the styles I have: they feature transparency, which breaks some other plugins, too.

**Comment by nimbling** [comment]
Hm! hold the presses, that was not it: it now only lists the colors that are applied in the current page. Not the colors in the document list, nor the colors availoable through libraries.

**Comment by nimbling** [comment]
from the readme: "we can only find styles that are on the canvas."

MY BAD, SORRY
